name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './front'
    steps:
      - uses: actions/checkout@v7

      - name: Set Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x

      - name: Run install
        run: yarn install

      - name: Build production bundle
        run: yarn build

      - name: Test the app
        run: yarn test
